# forma simples, imprimindo em sequência

print("O dono do hotel é supersticioso, não temos o 13º andar!")
print()

print("1º andar.")
print("2º andar.")
print("3º andar.")
print("4º andar.")
print("5º andar.")
print("6º andar.")
print("7º andar.")
print("8º andar.")
print("9º andar.")
print("10º andar.")
print("11º andar.")
print("12º andar.")
print("14º andar.")
print("15º andar.")
print("16º andar.")
print("17º andar.")
print("18º andar.")
print("19º andar.")
print("20º andar.")